//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1008.
// 
#pragma warning disable 1591

namespace krsclient.net.dk.nspop.batchcopy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StamdataReplicationSoap11Binding", Namespace="http://nsi.dk/2011/10/21/StamdataKrs/")]
    public partial class StamdataReplicationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Security securityValueField;
        
        private Header headerValueField;
        
        private System.Threading.SendOrPostCallback replicateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StamdataReplicationService() {
            this.Url = global::krsclient.net.Properties.Settings.Default.krsclient_net_dk_nspop_batchcopy_StamdataReplicationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Security SecurityValue {
            get {
                return this.securityValueField;
            }
            set {
                this.securityValueField = value;
            }
        }
        
        public Header HeaderValue {
            get {
                return this.headerValueField;
            }
            set {
                this.headerValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event replicateCompletedEventHandler replicateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://nsi.dk/2011/10/21/StamdataKrs/replicate", RequestElementName="ReplicationRequest", RequestNamespace="http://nsi.dk/2011/10/21/StamdataKrs/", ResponseElementName="ReplicationResponse", ResponseNamespace="http://nsi.dk/2011/10/21/StamdataKrs/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement replicate([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string register, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string datatype, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] uint version, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string offset, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] uint maxRecords, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool maxRecordsSpecified) {
            object[] results = this.Invoke("replicate", new object[] {
                        register,
                        datatype,
                        version,
                        offset,
                        maxRecords,
                        maxRecordsSpecified});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void replicateAsync(string register, string datatype, uint version, string offset, uint maxRecords, bool maxRecordsSpecified) {
            this.replicateAsync(register, datatype, version, offset, maxRecords, maxRecordsSpecified, null);
        }
        
        /// <remarks/>
        public void replicateAsync(string register, string datatype, uint version, string offset, uint maxRecords, bool maxRecordsSpecified, object userState) {
            if ((this.replicateOperationCompleted == null)) {
                this.replicateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnreplicateOperationCompleted);
            }
            this.InvokeAsync("replicate", new object[] {
                        register,
                        datatype,
                        version,
                        offset,
                        maxRecords,
                        maxRecordsSpecified}, this.replicateOperationCompleted, userState);
        }
        
        private void OnreplicateOperationCompleted(object arg) {
            if ((this.replicateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.replicateCompleted(this, new replicateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "", IsNullable=false)]
    public partial class Security : System.Web.Services.Protocols.SoapHeader {
        
        private Timestamp timestampField;
        
        private AssertionType assertionField;
        
        private Signature signatureField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
            "d")]
        public Timestamp Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
        public AssertionType Assertion {
            get {
                return this.assertionField;
            }
            set {
                this.assertionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public Signature Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
        "d")]
    public partial class Timestamp {
        
        private System.DateTime createdField;
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class NameIDType {
        
        private SubjectIdentifierType formatField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubjectIdentifierType Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public enum SubjectIdentifierType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:cprnumber")]
        medcomcprnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:ynumber")]
        medcomynumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:pnumber")]
        medcompnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:skscode")]
        medcomskscode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:cvrnumber")]
        medcomcvrnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:communalnumber")]
        medcomcommunalnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:locationnumber")]
        medcomlocationnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:itsystemname")]
        medcomitsystemname,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:other")]
        medcomother,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class AssertionType {
        
        private string issuerField;
        
        private Subject subjectField;
        
        private Conditions conditionsField;
        
        private AttributeStatement[] attributeStatementField;
        
        private Signature signatureField;
        
        private System.DateTime issueInstantField;
        
        private decimal versionField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string Issuer {
            get {
                return this.issuerField;
            }
            set {
                this.issuerField = value;
            }
        }
        
        /// <remarks/>
        public Subject Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public Conditions Conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeStatement")]
        public AttributeStatement[] AttributeStatement {
            get {
                return this.attributeStatementField;
            }
            set {
                this.attributeStatementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public Signature Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime IssueInstant {
            get {
                return this.issueInstantField;
            }
            set {
                this.issueInstantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class Subject {
        
        private NameIDType nameIDField;
        
        private SubjectConfirmation subjectConfirmationField;
        
        /// <remarks/>
        public NameIDType NameID {
            get {
                return this.nameIDField;
            }
            set {
                this.nameIDField = value;
            }
        }
        
        /// <remarks/>
        public SubjectConfirmation SubjectConfirmation {
            get {
                return this.subjectConfirmationField;
            }
            set {
                this.subjectConfirmationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class SubjectConfirmation {
        
        private ConfirmationMethod confirmationMethodField;
        
        private SubjectConfirmationData subjectConfirmationDataField;
        
        /// <remarks/>
        public ConfirmationMethod ConfirmationMethod {
            get {
                return this.confirmationMethodField;
            }
            set {
                this.confirmationMethodField = value;
            }
        }
        
        /// <remarks/>
        public SubjectConfirmationData SubjectConfirmationData {
            get {
                return this.subjectConfirmationDataField;
            }
            set {
                this.subjectConfirmationDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public enum ConfirmationMethod {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:oasis:names:tc:SAML:2.0:cm:holder-of-key")]
        urnoasisnamestcSAML20cmholderofkey,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class SubjectConfirmationData {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsernameToken", typeof(UsernameToken), Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        [System.Xml.Serialization.XmlElementAttribute("KeyInfo", typeof(KeyInfo), Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class UsernameToken {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName")]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyInfo {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string), DataType="NMTOKEN")]
        [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509Data))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509Data {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string), DataType="NMTOKEN")]
        [System.Xml.Serialization.XmlElementAttribute("X509Certificate", typeof(byte[]), DataType="base64Binary")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class Conditions {
        
        private System.DateTime notBeforeField;
        
        private System.DateTime notOnOrAfterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime NotBefore {
            get {
                return this.notBeforeField;
            }
            set {
                this.notBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime NotOnOrAfter {
            get {
                return this.notOnOrAfterField;
            }
            set {
                this.notOnOrAfterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class AttributeStatement {
        
        private Attribute[] attributeField;
        
        private AttributeStatementID idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute")]
        public Attribute[] Attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AttributeStatementID id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class Attribute {
        
        private string attributeValueField;
        
        private AttributeName nameField;
        
        private SubjectIdentifierType nameFormatField;
        
        private bool nameFormatFieldSpecified;
        
        /// <remarks/>
        public string AttributeValue {
            get {
                return this.attributeValueField;
            }
            set {
                this.attributeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AttributeName Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubjectIdentifierType NameFormat {
            get {
                return this.nameFormatField;
            }
            set {
                this.nameFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NameFormatSpecified {
            get {
                return this.nameFormatFieldSpecified;
            }
            set {
                this.nameFormatFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public enum AttributeName {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:IDCardID")]
        sosiIDCardID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:IDCardVersion")]
        sosiIDCardVersion,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:IDCardType")]
        sosiIDCardType,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:AuthenticationLevel")]
        sosiAuthenticationLevel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:OCESCertHash")]
        sosiOCESCertHash,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserCivilRegistrationNumber")]
        medcomUserCivilRegistrationNumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserGivenName")]
        medcomUserGivenName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserSurName")]
        medcomUserSurName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserEmailAddress")]
        medcomUserEmailAddress,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserRole")]
        medcomUserRole,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserOccupation")]
        medcomUserOccupation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserAuthorizationCode")]
        medcomUserAuthorizationCode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:CareProviderID")]
        medcomCareProviderID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:CareProviderName")]
        medcomCareProviderName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:ITSystemName")]
        medcomITSystemName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public enum AttributeStatementID {
        
        /// <remarks/>
        IDCardData,
        
        /// <remarks/>
        UserLog,
        
        /// <remarks/>
        SystemLog,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class Signature {
        
        private SignedInfo signedInfoField;
        
        private byte[] signatureValueField;
        
        private KeyInfo keyInfoField;
        
        private string idField;
        
        /// <remarks/>
        public SignedInfo SignedInfo {
            get {
                return this.signedInfoField;
            }
            set {
                this.signedInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
            }
        }
        
        /// <remarks/>
        public KeyInfo KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfo {
        
        private CanonicalizationMethod canonicalizationMethodField;
        
        private SignatureMethod signatureMethodField;
        
        private Reference[] referenceField;
        
        /// <remarks/>
        public CanonicalizationMethod CanonicalizationMethod {
            get {
                return this.canonicalizationMethodField;
            }
            set {
                this.canonicalizationMethodField = value;
            }
        }
        
        /// <remarks/>
        public SignatureMethod SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public Reference[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class CanonicalizationMethod {
        
        private CanonicalizationMethodAlgorithm algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CanonicalizationMethodAlgorithm Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public enum CanonicalizationMethodAlgorithm {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/TR/2001/REC-xml-c14n-20010315")]
        httpwwww3orgTR2001RECxmlc14n20010315,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2001/10/xml-exc-c14n#")]
        httpwwww3org200110xmlexcc14n,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureMethod {
        
        private SignatureMethodAlgorithm algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SignatureMethodAlgorithm Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public enum SignatureMethodAlgorithm {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#rsa-sha1")]
        httpwwww3org200009xmldsigrsasha1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class Reference {
        
        private Transforms transformsField;
        
        private DigestMethod digestMethodField;
        
        private byte[] digestValueField;
        
        private string uRIField;
        
        /// <remarks/>
        public Transforms Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        public DigestMethod DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class Transforms {
        
        private TransformsTransform[] transformField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transform")]
        public TransformsTransform[] Transform {
            get {
                return this.transformField;
            }
            set {
                this.transformField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class TransformsTransform {
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DigestMethod {
        
        private DigestMethodAlgorithm algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DigestMethodAlgorithm Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public enum DigestMethodAlgorithm {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#sha1")]
        httpwwww3org200009xmldsigsha1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd", IsNullable=false)]
    public partial class Header : System.Web.Services.Protocols.SoapHeader {
        
        private int securityLevelField;
        
        private bool securityLevelFieldSpecified;
        
        private TimeOut timeOutField;
        
        private bool timeOutFieldSpecified;
        
        private Linking linkingField;
        
        private FlowStatus flowStatusField;
        
        private bool flowStatusFieldSpecified;
        
        private Priority priorityField;
        
        private bool priorityFieldSpecified;
        
        private RequireNonRepudiationReceipt requireNonRepudiationReceiptField;
        
        private bool requireNonRepudiationReceiptFieldSpecified;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public int SecurityLevel {
            get {
                return this.securityLevelField;
            }
            set {
                this.securityLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SecurityLevelSpecified {
            get {
                return this.securityLevelFieldSpecified;
            }
            set {
                this.securityLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TimeOut TimeOut {
            get {
                return this.timeOutField;
            }
            set {
                this.timeOutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeOutSpecified {
            get {
                return this.timeOutFieldSpecified;
            }
            set {
                this.timeOutFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Linking Linking {
            get {
                return this.linkingField;
            }
            set {
                this.linkingField = value;
            }
        }
        
        /// <remarks/>
        public FlowStatus FlowStatus {
            get {
                return this.flowStatusField;
            }
            set {
                this.flowStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlowStatusSpecified {
            get {
                return this.flowStatusFieldSpecified;
            }
            set {
                this.flowStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Priority Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public RequireNonRepudiationReceipt RequireNonRepudiationReceipt {
            get {
                return this.requireNonRepudiationReceiptField;
            }
            set {
                this.requireNonRepudiationReceiptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequireNonRepudiationReceiptSpecified {
            get {
                return this.requireNonRepudiationReceiptFieldSpecified;
            }
            set {
                this.requireNonRepudiationReceiptFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
    public enum TimeOut {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("480")]
        Item480,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1440")]
        Item1440,
        
        /// <remarks/>
        unbound,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
    public partial class Linking {
        
        private string flowIDField;
        
        private string messageIDField;
        
        private string inResponseToMessageIDField;
        
        /// <remarks/>
        public string FlowID {
            get {
                return this.flowIDField;
            }
            set {
                this.flowIDField = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string InResponseToMessageID {
            get {
                return this.inResponseToMessageIDField;
            }
            set {
                this.inResponseToMessageIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
    public enum FlowStatus {
        
        /// <remarks/>
        flow_running,
        
        /// <remarks/>
        flow_finalized_succesfully,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
    public enum Priority {
        
        /// <remarks/>
        AKUT,
        
        /// <remarks/>
        HASTER,
        
        /// <remarks/>
        RUTINE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
    public enum RequireNonRepudiationReceipt {
        
        /// <remarks/>
        yes,
        
        /// <remarks/>
        no,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void replicateCompletedEventHandler(object sender, replicateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class replicateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal replicateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591